server:
  port: 4014
  servlet:
    context-path: /
spring:
  datasource:
    master:
      driverClassName: oracle.jdbc.driver.OracleDriver
      initial-size: 5
      jdbcUrl: jdbc:oracle:thin:@172.31.27.152:1521/xe
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      password: poly_web
      username: oracle
    slave1:
      driverClassName: oracle.jdbc.driver.OracleDriver
      initial-size: 5
      jdbcUrl: jdbc:oracle:thin:@172.31.27.152:1521/xe
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      password: poly_web
      username: oracle
  redis:
    host: 47.108.31.123
    password: hxfRedis
    port: 6379
    database: 6
mvc:
  view:
    prefix: /WEB-INF/jsp
    suffix: .jsp

logging:
  config: classpath:logback.xml

file:
  #文件访问地址
  imgUrl: http://192.168.1.111:9888/
  #文件下载缓存目录
  temp: /home/file/
