server:
  port: 4014
  servlet:
    context-path: /
spring:
    redis:
      host: 47.108.31.123 #地址
      port: 6379 #端口
      password: hxfRedis
      timeout: 10000 # 连接超时时间（毫秒）
      database: 15 #默认数据库
      jedis:
        pool:
          max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
          max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 10 # 连接池中的最大空闲连接
          min-idle: 0 # 连接池中的最小空闲连接
          time-between-eviction-runs: -1 #逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1

mvc:
  view:
    prefix: /WEB-INF/jsp
    suffix: .jsp
logging:
  config: classpath:logback.xml
