server:
  port: 8817
  servlet:
    context-path: /
spring:
  datasource:
#    master:
#      driverClassName: com.mysql.jdbc.Driver
#      initial-size: 5
#      jdbcUrl: jdbc:mysql://192.168.1.110:3306/channel_plat?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimeZone=GMT+8
#      max-idle: 10
#      max-wait: 10000
#      min-idle: 5
#      password: Pay2025!
#      username: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.110:3306/channel_plat?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimeZone=GMT+8
    username: root
    password: Pay2025!
  redis:
    host: 192.168.1.110
    password: hxfRedis
    port: 6379
    database: 6
mvc:
  view:
    prefix: /WEB-INF/jsp
    suffix: .jsp

logging:
  config: classpath:logback.xml